services:
  - type: web
    name: google-maps-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /tmp/ms-playwright
      playwright install --with-deps chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SESSION_SECRET
        generateValue: true
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/ms-playwright
    autoDeploy: true
